const SORT_PRODUCT = "SORT_PRODUCT";
const SORT_PRODUCT_SMALLEST = "SORT_PRODUCT_SMALLEST";
const ADD_PRODUCT = "ADD_PRODUCT";
const SORT_NOVELTY = "SORT_NOVELTY";
const SORT_POPULARITY = "SORT_POPULARITY";
const RETURN_DEFAULT = "RETURN_DEFAULT";
const SALE_PRODUCTS = "SALE_PRODUCTS";
const TYPE_PRODUCTS = "TYPE_PRODUCTS";
const SHOW_PRODUCT = "SHOW_PRODUCT";
export default {
  SORT_PRODUCT,
  ADD_PRODUCT,
  SORT_PRODUCT_SMALLEST,
  SORT_NOVELTY,
  SORT_POPULARITY,
  RETURN_DEFAULT,
  SALE_PRODUCTS,
  TYPE_PRODUCTS,
  SHOW_PRODUCT
};
