const ADD_PRODUCT = "ADD_PRODUCT";
const RESET_PRODUCTS = "RESET_PRODUCTS";
const SORT_PRODUCT = "SORT_PRODUCT";
const SORT_PRODUCT_SMALLEST = "SORT_PRODUCT_SMALLEST";
const RETURN_DEFAULT = "RETURN_DEFAULT";
const SHOW_PRODUCT = "SHOW_PRODUCT";
const RETURN_DEFAULT_SEX = "RETURN_DEFAULT_SEX";
const SHOW_PRODUCT_SIZE = "SHOW_PRODUCT_SIZE";
const SHOW_PRODUCT_PRICE = "SHOW_PRODUCT_PRICE";
const SHOW_PRODUCT_DETAILS = "SHOW_PRODUCT_DETAILS";
const ADD_PRODUCT_TO_FAVOURITE = "ADD_PRODUCT_TO_FAVOURITE";
const ADD_TO_SHOP_LIST = "ADD_TO_SHOP_LIST";
const DELETE_FROM_SHOP_LIST = "DELETE_FROM_SHOP_LIST";
const ADD_THE_SAME_PRODUCT = "ADD_THE_SAME_PRODUCT";
const UPDATE_COUNTER = "UPDATE_COUNTER";
const PRODUCT_DATA = "PRODUCT_DATA";
const PRODUCT_DATA_PRICE = "PRODUCT_DATA_PRICE";
const PAYMENT_METHOD = "PAYMENT_METHOD";
const CLEAR_SHOP = "CLEAR_SHOP";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";
const SHOW_MARK = "SHOW_MARK";
const USER_DATA = "USER_DATA";
const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS";
const SHOW_SIZE = "SHOW_SIZE";

export default {
  ADD_PRODUCT,
  RESET_PRODUCTS,
  SORT_PRODUCT,
  RETURN_DEFAULT_SEX,
  SORT_PRODUCT_SMALLEST,
  RETURN_DEFAULT,
  SHOW_PRODUCT,
  SHOW_PRODUCT_SIZE,
  SHOW_PRODUCT_PRICE,
  SHOW_PRODUCT_DETAILS,
  ADD_PRODUCT_TO_FAVOURITE,
  ADD_TO_SHOP_LIST,
  DELETE_FROM_SHOP_LIST,
  ADD_THE_SAME_PRODUCT,
  UPDATE_COUNTER,
  PRODUCT_DATA,
  PRODUCT_DATA_PRICE,
  PAYMENT_METHOD,
  CLEAR_SHOP,
  SEARCH_PRODUCT,
  SHOW_MARK,
  USER_DATA,
  SHOW_ALL_PRODUCTS,
  SHOW_SIZE
};
