const SORT_PRODUCT = "SORT_PRODUCT";
const SORT_PRODUCT_SMALLEST = "SORT_PRODUCT_SMALLEST";
const RETURN_DEFAULT = "RETURN_DEFAULT";
const SHOW_PRODUCT = "SHOW_PRODUCT";
const RETURN_DEFAULT_SEX = "RETURN_DEFAULT_SEX";
const SHOW_PRODUCT_SIZE = "SHOW_PRODUCT_SIZE";
const SHOW_PRODUCT_PRICE = " SHOW_PRODUCT_PRICE";
export default {
  SORT_PRODUCT,
  RETURN_DEFAULT_SEX,
  SORT_PRODUCT_SMALLEST,
  RETURN_DEFAULT,
  SHOW_PRODUCT,
  SHOW_PRODUCT_SIZE,
  SHOW_PRODUCT_PRICE
};
